2025-03-14 20:31:16,989 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28293 (tickets.py:325)
2025-03-14 20:31:19,217 - bot - INFO - Пользователь anarchowitz пытается закрыть тикет anarcho-ticket-28293 (tickets.py:382)
2025-03-14 20:31:20,844 - bot - INFO - Пользователь anarchowitz подтвердил закрытие тикета anarcho-ticket-28293 (tickets.py:405)
2025-03-14 20:45:05,178 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28294 (tickets.py:325)
2025-03-14 20:45:11,033 - bot - INFO - Пользователь anarchowitz пытается закрыть тикет anarcho-ticket-28294 (tickets.py:382)
2025-03-14 20:45:12,102 - bot - INFO - Пользователь anarchowitz подтвердил закрытие тикета с причиной anarcho-ticket-28294 (tickets.py:489)
2025-03-14 20:50:14,468 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28295 (tickets.py:323)
2025-03-14 20:51:03,029 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28296 (tickets.py:323)
2025-03-14 20:51:03,242 - bot - ERROR - Ошибка при взятии тикета ticket-28296: 'MessageInteraction' object has no attribute 'send_message' (tickets.py:376)
2025-03-14 20:52:52,280 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:52:52,475 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:376)
2025-03-14 20:54:03,539 - bot - INFO - Пользователь anarchowitz пытается закрыть тикет ticket-28297 (tickets.py:380)
2025-03-14 20:54:07,016 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:54:07,239 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:376)
2025-03-14 20:54:32,101 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:54:32,300 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:377)
2025-03-14 20:54:41,429 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:54:41,633 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:377)
2025-03-14 20:54:43,753 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:54:43,956 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:377)
2025-03-14 20:55:29,310 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:55:29,513 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:378)
2025-03-14 20:55:48,343 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:55:48,541 - bot - ERROR - Ошибка при взятии тикета ticket-28297: This interaction has already been responded to before (tickets.py:378)
2025-03-14 20:57:14,267 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:57:14,488 - bot - ERROR - Ошибка при взятии тикета ticket-28297: 'MessageInteraction' object has no attribute 'send_message' (tickets.py:377)
2025-03-14 20:59:14,856 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28297 (tickets.py:323)
2025-03-14 20:59:15,063 - bot - ERROR - Error in on_button_click: This interaction has already been responded to before (tickets.py:330)
2025-03-14 20:59:16,525 - bot - ERROR - Ошибка при взятии тикета ticket-28297: cannot access local variable 'taken_username' where it is not associated with a value (tickets.py:379)
2025-03-14 21:59:39,027 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28298 (tickets.py:323)
2025-03-14 21:59:41,165 - bot - INFO - Пользователь anarchowitz пытается закрыть тикет ticket-28298 (tickets.py:379)
2025-03-14 21:59:42,090 - bot - INFO - Пользователь anarchowitz подтвердил закрытие тикета с причиной ticket-28298 (tickets.py:486)
2025-03-14 21:59:45,987 - bot - INFO - Пользователь anarchowitz подтвердил закрытие тикета ticket-28298 (tickets.py:402)
2025-03-14 21:59:45,988 - bot - ERROR - Ошибка при закрытии тикета ticket-28298: 'NoneType' object is not subscriptable (tickets.py:482)
2025-03-14 22:01:16,977 - bot - INFO - Пользователь anarchowitz пытается взять тикет ticket-28299 (tickets.py:323)
2025-03-14 22:01:19,065 - bot - INFO - Пользователь anarchowitz пытается закрыть тикет ticket-28299 (tickets.py:379)
2025-03-14 22:01:19,910 - bot - INFO - Пользователь anarchowitz подтвердил закрытие тикета ticket-28299 (tickets.py:402)
